### PR TITLE
Switch from React to Preact (#28)

### PR DESCRIPTION
**Pull request by danielbayerlein**
PR for the issue #28 

- [x] Switch from React to Preact
- [x] Update Ruby dependencies
- [x] Update Node.js dependencies
- [x] Add Yarn support
- [x] Remove Sass warnings
- [x] Switch from `Chart.js` to `Recharts`
- [x] Generate `bundle.js`

| Before | After |
| ------ | ----- |
| 557 kB | 434 kB |

**Current bundle analyzed:**

```
lodash: 526.94 KB (38.8%)
precharts: 443.75 KB (32.7%)
d3-shape: 48.53 KB (3.58%)
d3-scale: 30.64 KB (2.26%)
es6-promise: 28.01 KB (2.06%)
preact: 22.8 KB (1.68%)
math-expression-evaluator: 17.28 KB (1.27%)
preact-compat: 16.15 KB (1.19%)
d3-time-format: 15.28 KB (1.13%)
d3-color: 14.43 KB (1.06%)
d3-interpolate: 14.15 KB (1.04%)
core-js: 13.2 KB (0.972%)
whatwg-fetch: 12.24 KB (0.902%)
d3-format: 11.44 KB (0.843%)
proptypes: 11.17 KB (0.823%)
d3-time: 10.78 KB (0.794%)
d3-array: 10.48 KB (0.772%)
lodash.indexof: 7.98 KB (0.588%)
object-path: 7.09 KB (0.522%)
preact-render-to-string: 6.96 KB (0.513%)
d3-collection: 5.49 KB (0.404%)
process: 5.17 KB (0.381%)
d3-path: 4.41 KB (0.325%)
reduce-css-calc: 4.13 KB (0.304%)
query-string: 2.01 KB (0.148%)
object-assign: 1.95 KB (0.143%)
reduce-function-call: 1.91 KB (0.141%)
raf: 1.84 KB (0.135%)
balanced-match: 1.13 KB (0.0835%)
classnames: 1.08 KB (0.0793%)
performance-now: 886 B (0.0637%)
webpack: 251 B (0.0181%)
strict-uri-encode: 182 B (0.0131%)
<self>: 57.59 KB (4.24%)
```

**Screenshots**

### CODE REVIEW

**Comment by danielbayerlein** [comment]
@eduardoboucas Ready for review. In a separate PR I can improve the application if you want.

**Comment by eduardoboucas** [comment]
Quite a big change, I see. Why did you swap the chart library?

**Comment by danielbayerlein** [comment]
`Chart.js` doesn't work very well with React or Preact.  For React it exist `react-chartjs` but not for Preact. It makes problems with the manipulated DOM. After a period change, I've always more charts and on mouseover the chart switch between the new and old chart. With `precharts` (based on `recharts`) I've chosen a compatible solution. If you are not happy with the solution, I can remove `precharts` again. But then we need a solution for the period change problem.

speedtracker

 The minified file size of `precharts` is 48 kB and from `Chart.js` 193 kB.

**Comment by eduardoboucas** [comment]
> Chart.js doesn't work very well with React or Preact

What makes you say that?

> For React it exist react-chartjs but not for Preact.

I'm not using any React wrapper for Chart.js, just using the original library. I thought that, for this reason, it would be carry on working regardless of the engine we use.

> It makes problems with the manipulated DOM. After a period change, I've always more charts and on mouseover the chart switch between the new and old chart.

Sorry, you lost me here. Could you elaborate?

Basically, I'm trying to avoid big changes here. The existing app is working fine as far as I'm concerned, the only reason I created this issue was to see if we could make a significant reduction in bundle size by switching to Preact.

**Comment by danielbayerlein** [comment]
> What makes you say that?

> I'm not using any React wrapper for Chart.js, just using the original library. I thought that, for this reason, it would be carry on working regardless of the engine we use.

Your current Chart.js implementation works with React that's true but unfortunately not with Preact.
You can see the result on the picture but you can also try it:

```bash
git clone https://github.com/danielbayerlein/speedtracker.git
git checkout 75ff7ed
```

I found no solution that worked.

> Sorry, you lost me here. Could you elaborate?

I'm not familiar with that. I'm not sure, but it looks like Chart.js changed the DOM. Perhaps Preact can not deal with this. Maybe you'll find a solution. In the picture you can see how the charts jump.

> Basically, I'm trying to avoid big changes here. The existing app is working fine as far as I'm concerned, the only reason I created this issue was to see if we could make a significant reduction in bundle size by switching to Preact.

I understand - no problem. I'm not angry with you. I just tried to improve SpeedTracker. 🤝

**Comment by ghost** [comment]
@danielbayerlein I've got my hands full at the moment but I may be able to help debug the issue. Could you rebase against the latest master so we don't get too stale on all the great work you've done porting thus far?

**Comment by danielbayerlein** [comment]
@jhabdas I'll rebase the latest master. The PR runs with `precharts` without problems. Only in association with `Chart.js` is there a problem. But I'm not sure if @eduardoboucas ever merge the PR.

**Comment by danielbayerlein** [comment]
@jhabdas BTW: The PR runs with `precharts` without problems. Only in association with `Chart.js` is there a problem.

**Comment by eduardoboucas** [comment]
Sorry for being radio silent for so long, this one has somehow gone out of my radar. I'm keen on switching to Preact, but I'm still skeptical about moving away from Chart.js.

The dashboard relies a lot on it and having to refactor + learn a new API does have its price, particularly when in theory there's no reason for it not to work with Preact. If we do come to the conclusion that it absolutely doesn't, I'm not sure I'm in favour of ditching React. 

Thanks both for your help on this, really appreciate the effort!

**Comment by danielbayerlein** [comment]
@jhabdas Solving the conflicts is more difficult than imagined. I don't want to spend more time. It's time to close the PR.

**Pull request closed without merging**
