### PR TITLE
Fix webpagetest url reference

### PR DESCRIPTION
**Pull request by fabioscsilva**
This is to fix the webpage test url when you click on a test. Right now the url opened isn't the right one with the timestamp from the chart.

### CODE REVIEW

**Comment by eduardoboucas** [comment]
Are you able to replicate this issue on the [demo site](https://demo.speedtracker.org/)? If so, can you tell me the steps you need to follow?

Thanks!

**Comment by fabioscsilva** [comment]
Sure.

Steps:
- Change to **in the last month**
- Choose a point (for instance the last: _9/5/2017 10:14:42_ 
- If you click you go to this url - https://www.webpagetest.org/result/170429_14_9N5/
- And the date of the test is different - _2017-4-29 06:21:20_

Let me know if you need more details

**Comment by fabioscsilva** [comment]
@eduardoboucas Do you need more info about it?

**Comment by eduardoboucas** [comment]
No, sorry! It looks great, I just hadn't had the chance to look into this. Will do so in a few days. 

Thanks again!

**Comment by eduardoboucas** [comment]
I was finally able to merge it and release [1.2.3](https://github.com/speedtracker/speedtracker/releases/tag/1.2.3).

Works like a charm! Thanks so much @fabioscsilva and sorry for the embarrassingly long time it took me to review.

**Pull request merged**
