### PR TITLE
Add Analytics Tracking

### LINKED ISSUE #57: Integrate Tracking with Google Analytics
Pull request to follow shortly...

### PR DESCRIPTION
**Pull request by ghost**
adds google analytics tracking using the async tracking snippet

closes #57

https://developers.google.com/analytics/devguides/collection/analyticsjs/

### CODE REVIEW

**Comment by eduardoboucas** [comment]
Great idea! Only one tiny detail: we use camel case for variables in profiles, but you're adding a snake case here. Should we consolidate here?

**Comment by ghost** [comment]
Force of habit, and a bit more in line with what [SEO Tag Gem](https://github.com/jekyll/jekyll-seo-tag/) and other core friends of Jekyll are doing. But consistency is key. Updating.

**Comment by ghost** [comment]
Actually. I'm going to renege my last comment. We should standardize on snake. I'm doing the research now.

**Comment by ghost** [comment]
Here it is: https://github.com/bbatsov/ruby-style-guide#naming

> Use `snake_case` for symbols, methods and variables.

Because Jekyll was born out of the Rails community, and enjoys many of the same Rails community tooling (e.g. Sprockets, etc.) we should standardize on lower snake.

Additionally, the [most popular Jekyll themes](https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml) use lower snake for their configs, and individuals will be copying those. If we don't go lower snake we'll end up seeing configs in the wild sharing both, which nobody wants I'm sure.

Lastly, users (like me) who intend to use SpeedTracker on CloudCannon will benefit from automatic spacing and pluralization of metadata when using lower snake case: https://docs.cloudcannon.com/editing/front-matter/

**Comment by eduardoboucas** [comment]
That's fine with me. As for changing `wptUrl` accordingly, I wrote some thoughts on #59.

**Comment by ghost** [comment]
Still looking for a merge on this. Please let me know if there is any actionable feedback.

**Comment by eduardoboucas** [comment]
Sorry for the delay, been distracted with other things. I'll merge and release later today.

**Comment by eduardoboucas** [comment]
Shamefully late, merged!

**Pull request merged**
